server:
  port: 8081

spring:
  application:
    name: flight-service

  datasource:
    url: jdbc:postgresql://postgres:5432/aerostream
    username: aerostream
    password: aerostream

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    level: "%5p [cid=%X{correlationId}]"
