server:
  port: 8084

spring:
  application:
    name: kpi-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:airline_ops}
    username: ${MYSQL_USER:airline_user}
    password: ${MYSQL_PASSWORD:airline_password}

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    level: "%5p [cid=%X{correlationId}]"
