server:
  port: 8084

spring:
  application:
    name: kpi-service

  datasource:
    url: jdbc:postgresql://postgres:5432/aerostream
    username: aerostream
    password: aerostream

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    level: "%5p [cid=%X{correlationId}]"
